"""post1.0

Revision ID: 1d0831e9ac5a
Revises: None
Create Date: 2016-09-04 23:03:12.681530

"""

# revision identifiers, used by Alembic.
revision = '1d0831e9ac5a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
