"""avatar

Revision ID: 4a95cc52c7ff
Revises: 45a49f358a28
Create Date: 2016-09-03 20:10:45.541001

"""

# revision identifiers, used by Alembic.
revision = '4a95cc52c7ff'
down_revision = '45a49f358a28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
