"""init

Revision ID: 87ec3371bc3
Revises: None
Create Date: 2016-09-02 19:13:16.470503

"""

# revision identifiers, used by Alembic.
revision = '87ec3371bc3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
